Inventary-App/Inventary-App/Models/ErrorViewModel.cs
using System;

namespace Inventary_App.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Inventary-App/Inventary-App/Controllers/HomeController.cs
using Inventary_App.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Inventary_App.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            //return View();
            return Redirect("/Inventary/LogIn");
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Inventary-App/Inventary-App/Controllers/InventaryController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Inventary_App.Controllers
{
    public class InventaryController : Controller
    {
        public static InventaryController Instance { get; set; } = new InventaryController();

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult LogIn()
        {
            return View();
        }

        public IActionResult ForgotPassword()
        {
            return View();
        }
    }
}

Inventary-App/Inventary-App/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Inventary-App/Inventary-App/Views/Inventary/ForgotPassword.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@{
    ViewData["Title"] = "Forgot Password";
}

<link href="~/css/icons.css" rel="stylesheet" />

<body class="bg-info">
    <div class="col-12 col-md-9 col-lg-7 col-xl-6 m-auto pt-5 mt-lg-5">
        <form id="form" class="bg-white mt-5" style="border-radius: 20px">
            <div class="group-separation">
                <ion-icon name="lock-closed"></ion-icon>
            </div>
            <div class="mb-4">
                <p class="text-muted text-center">Enter your email and we'll send you a link to reset your password</p>
            </div>
            <div class="mb-4 ml-4 mr-4">
                <input type="email" name="email" id="email" placeholder="Your@email.com" class="form-control form-control-lg rounded" />
            </div>
            <div class="pb-4 ml-4 mr-4">
                <input type="submit" value="Submit" class="btn btn-success btn-block btn-lg gradient-custom-4 font-weight-bold text-white rounded-pill" />
            </div>
            <p class="text-center pb-2"><a asp-action="LogIn" asp-controller="Inventary">Back to Login</a></p>
        </form>
    </div>

    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="~/js/ForgotPassword.js" type="module"></script>
</body>

Inventary-App/Inventary-App/Views/Inventary/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@{
    ViewData["Title"] = "Sign Up";
}



<body class="bg-info">
    <div class="col-12 col-md-9 col-lg-7 col-xl-6 m-auto w-100 pt-4 mt-lg-5 m-sm-auto">
        <form id="form" class="bg-white my-auto my-sm-auto" style="border-radius: 20px">
            <div class="mt-4 mb-4">
                <h1 class="font-weight-bold text-center display-4">Sign Up</h1>
            </div>
            <div class="mt-4 mb-4 ml-4 mr-4 pt-4">
                <h5 class="font-weight-bold" for="first-name">Usuario</h5>
                <input type="text" name="user" id="userName" placeholder="Tu usuario" class="form-control form-control-lg rounded" required />
            </div>
            <div class="mb-4 ml-4 mr-4">
                <h5 class="font-weight-bold" for="email">Email</h5>
                <input type="email" name="email" id="email" placeholder="Your@email.com" class="form-control form-control-lg rounded" required />
            </div>
            <div class="mb-5 ml-4 mr-4">
                <h5 class="font-weight-bold" for="password">Contraseña</h5>
                <input type="password" name="password" id="password" placeholder="Tu contraseña" class="form-control form-control-lg rounded" required />
            </div>
            <div class="mb-3 ml-4 mr-4 pb-2">
                <input type="submit" value="Register" class="btn btn-primary btn-block btn-lg gradient-custom-4 font-weight-bold text-white rounded-pill" required />
            </div>
            <p class="text-center pb-2 pt-2 text-muted">Have already an account? <a asp-action="LogIn" asp-controller="Inventary">Log In</a></p>

            @*<p class="text-center pb-2 text-muted">Have already an account? <a href="#" class="fw-bold text-body"><u>Login here</u></a></p>*@

            @*<a asp-action="LogIn" asp-controller="Inventary">Home</a>*@
        </form>
    </div>

    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="~/js/index.js" type="module"></script>
</body>

Inventary-App/Inventary-App/Views/Inventary/LogIn.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


@{
    ViewData["Title"] = "Log In";
}

<body class="bg-info">
    <div class="col-12 col-md-9 col-lg-7 col-xl-6 m-auto pt-5 mt-lg-5">
        <form id="form" class="bg-white mt-5" style="border-radius: 20px">
            <div class="mt-4 mb-4">
                <h1 class="font-weight-bold text-center display-4">Log In</h1>
            </div>
            <div class="mb-4 ml-4 mr-4">
                <h5 class="font-weight-bold" for="email">Email</h5>
                <input type="email" name="email" id="email" placeholder="Your@email.com" class="form-control form-control-lg rounded" />
            </div>
            <div class="mb-5 ml-4 mr-4">
                <h5 class="font-weight-bold" for="password">Contraseña</h5>
                <input type="password" name="password" id="password" placeholder="Tu contraseña" class="form-control form-control-lg rounded" />
            </div>
            <div class="ml-4 mr-4 pb-2 pb-4">
                <input type="submit" value="Submit" class="btn btn-primary btn-block btn-lg gradient-custom-4 font-weight-bold text-white rounded-pill" />
            </div>
            <div class="pb-1">
                <p class="text-center pb-1 text-muted">Don't have an account? <a asp-action="Index" asp-controller="Inventary">Sign Up</a></p>
            </div>
            <p class="text-center pb-2"><a asp-action="ForgotPassword" asp-controller="Inventary">Forgot your password?</a></p>
        </form>
    </div>

    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="~/js/login.js" type="module"></script>
</body>

Inventary-App/Inventary-App/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Inventary_App</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    @*<header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Inventary_App</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>*@
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @*<footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Inventary_App - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>